### ISSUE TITLE
add rating AKA a new library to the project and make sure it is working

### ISSUE THREAD

**Issue by SepidehAyani** [SepidehAyani/mixitup#52]
use this link for reference: 
https://openbase.com/js/bootstrap-rating
or this
https://www.npmjs.com/package/raty-js

**Comment by crosenfrisk** [comment]
Added routes for rating in controllers and index.js, ran npm i raty-js, which will need to be done on other devices and communicated in the README. 

Added rating input to single-drink.handlebars and imported script as required by npm package for <jquery.raty.js>. 

Created Rating.js model, and relationships within index.js. 

NO SEEDS yet. 

Added images star-on and star-off which are actually heart icons/png files located within /images. 

Suggestion to remove _upvote_ and _delete routes_/functions from all areas of application, or comment out for future development -- but they can stay too. Currently throw an error.

Thank you.

**Comment by crosenfrisk** [comment]
Note: I believe I have all the functions, imports, and files that we need for it to run, and consulting [npm](https://www.npmjs.com/package/raty-js) guide I created .png "star-on" and "star-off" for image icons (which are actually hearts, but the documentation says the words need to be star-on/star-off)... however all I see on my end when I run the script is .img placeholders. The directory I am pointing to is /images, just like all our other files.

I would love your help with this, since I am unable to complete it tonight. I will look at it again tomorrow, but if I cannot complete it before 10 a.m. I will need your help to finalize before deployment.
